ALTER TABLE [dbo].[TRT_OBSERVATIONS]
DROP COLUMN CORRECTED_DATE;
GO

ALTER TABLE [dbo].[TRT_OBSERVATIONS]
ALTER COLUMN [OBSERVATION_TIME] datetimeoffset;
GO

ALTER TABLE [dbo].[TRT_OBSERVATIONS]
ALTER COLUMN [OBSERVATION_DATE] datetimeoffset;
GO

ALTER TABLE [dbo].[TRT_OBSERVATIONS]
ADD CORRECTED_DATE AS 
    CASE 
        WHEN OBSERVATION_TIME IS NULL THEN OBSERVATION_DATE
        WHEN CONVERT(time, OBSERVATION_TIME) > CONVERT(time, '12:00:00') THEN OBSERVATION_DATE
        ELSE DATEADD(day, 1, OBSERVATION_DATE)
    END;
GO