UPDATE dbo.TRT_OBSERVATIONS

SET OBSERVATION_DATE = 
    CASE 
        WHEN OBSERVATION_TIME IS NOT NULL 
        THEN CAST(CONVERT(varchar(10), OBSERVATION_DATE, 120) + ' ' + CONVERT(varchar(8), OBSERVATION_TIME, 108) AS datetime)
        ELSE OBSERVATION_DATE  -- Keep the original OBSERVATION_DATE if OBSERVATION_TIME is null
    END
WHERE OBSERVATION_TIME IS NOT NULL  -- Only update rows where OBSERVATION_TIME is not null

GO

-- copy date back to time field
UPDATE dbo.TRT_OBSERVATIONS

SET OBSERVATION_TIME = OBSERVATION_DATE
WHERE OBSERVATION_TIME IS NOT NULL

GO