name: 'Build docs pages'
on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    branches: [master]

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.12'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Build documentation
        run: |
          mkdir gh-pages
          touch gh-pages/.nojekyll
          uv run sphinx-build -b html docs _build
          cp -r _build/* gh-pages/
      - name: Deploy documentation
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
